CREATE TABLE EMPRESA (
    CNPJ VARCHAR2(14) NOT NULL,
    NOMEFANTASIA VARCHAR2(60),
    RAZAOSOCIAL VARCHAR2(120) NOT NULL,
    ENDERECO VARCHAR2(120) NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE CONTATOEMPRESA (
    EMPRESA VARCHAR2(14) NOT NULL,
    EMAIL VARCHAR2(60) NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    TELEFONE VARCHAR2(11),
    CONSTRAINT CONTATO_EMPRESA_PK PRIMARY KEY (EMPRESA, EMAIL),
    CONSTRAINT CONTATO_EMPRESA_FK1 FOREIGN KEY (EMPRESA)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE FORNECEDORA (
    CNPJ VARCHAR2(14) NOT NULL,
    CONSTRAINT FORNECEDORA_PK PRIMARY KEY (CNPJ),
    CONSTRAINT FORNECEDORA_FK1 FOREIGN KEY (CNPJ)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE CONTRATANTE (
    CNPJ VARCHAR2(14) NOT NULL,
    CONSTRAINT CONTRATANTE_PK PRIMARY KEY (CNPJ),
    CONSTRAINT CONTRATANTE_FK1 FOREIGN KEY (CNPJ)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE FESTA (
    ID NUMBER NOT NULL,
    CONTRATANTE VARCHAR2(14) NOT NULL,
    DATA DATE NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    HORAINICIO DATE NOT NULL,
    DURACAO DATE NOT NULL,
    TIPOFESTA VARCHAR2(8) NOT NULL,
    CONSTRAINT FESTA_PK PRIMARY KEY (ID),
    CONSTRAINT FESTA_UN1 UNIQUE (CONTRATANTE, DATA),
    CONSTRAINT FESTA_FK1 FOREIGN KEY (CONTRATANTE) REFERENCES CONTRATANTE(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FESTA_CK_TIPOFESTA CHECK(UPPER(TIPOFESTA) IN ('FESTFOOD', 'COQUETEL'))
);

CREATE TABLE FESTFOOD (
    FESTA NUMBER NOT NULL,
    PRECOINGRESSO NUMBER(6,2) NOT NULL,
    CONSTRAINT FESTFOOD_PK PRIMARY KEY (FESTA),
    CONSTRAINT FESTFOOD_FK1 FOREIGN KEY (FESTA) REFERENCES FESTA(ID) ON DELETE CASCADE,
    CONSTRAINT FESTFOOD_CK_PRECOINGRESSO CHECK(PRECOINGRESSO >= 0)
);

CREATE TABLE INGRESSO (
    FESTFOOD NUMBER NOT NULL,
    NUMERO NUMBER NOT NULL,
    CPFCOMPRADOR VARCHAR2(11) NOT NULL,
    CONSTRAINT INGRESSO_PK PRIMARY KEY (FESTFOOD, NUMERO),
    CONSTRAINT INGRESSO_FK1 FOREIGN KEY (FESTFOOD) REFERENCES FESTFOOD(FESTA) ON DELETE CASCADE
);

CREATE TABLE LOCAL (
    NOME VARCHAR2(60) NOT NULL,
    CIDADE VARCHAR2(40) NOT NULL,
    ESTADO VARCHAR2(19) NOT NULL,
    RUA VARCHAR2(40) NOT NULL,
    NUMERO NUMBER NOT NULL,
    MAXFREQUENTADORES NUMBER NOT NULL,
    POSSUIABERTURA CHAR(1) NOT NULL,
    DIARIALOCACAO NUMBER(9, 2) NOT NULL,
    CONSTRAINT LOCAL_CK_POSSUIABERTURA CHECK(UPPER(POSSUIABERTURA) IN ('V', 'F')),
    CONSTRAINT LOCAL_PK PRIMARY KEY (NOME, CIDADE)
);

CREATE TABLE LOCACAO (
    ID NUMBER NOT NULL,
    FESTFOOD NUMBER NOT NULL,
    NOMELOCAL VARCHAR2(60) NOT NULL,
    CIDADELOCAL VARCHAR2(40) NOT NULL,
    CONSTRAINT LOCACAO_PK PRIMARY KEY (ID),
    CONSTRAINT LOCACAO_UN1 UNIQUE(FESTFOOD, NOMELOCAL, CIDADELOCAL),
    CONSTRAINT LOCACAO_FK1 FOREIGN KEY (FESTFOOD)
        REFERENCES FESTFOOD(FESTA)
        ON DELETE CASCADE,
    CONSTRAINT LOCACAO_FK2 FOREIGN KEY (NOMELOCAL, CIDADELOCAL)
        REFERENCES LOCAL(NOME, CIDADE)
        ON DELETE CASCADE
);

CREATE TABLE LOTE (
    LOCACAO NUMBER NOT NULL,
    NUMERO NUMBER NOT NULL,
    FORNECEDORA VARCHAR2(14),
    PRECO NUMBER(9, 2) NOT NULL,
    LARGURA NUMBER(6,2),
    COMPRIMENTO NUMBER(6,2),
    CONSTRAINT LOTE_CK_LARGURA CHECK(LARGURA > 0),
    CONSTRAINT LOTE_CK_COMPRIMENTO CHECK(COMPRIMENTO > 0),
    CONSTRAINT LOTE_PK PRIMARY KEY (NUMERO, LOCACAO),
    CONSTRAINT LOTE_FK1 FOREIGN KEY (LOCACAO)
        REFERENCES LOCACAO(ID) ON DELETE CASCADE,
    CONSTRAINT LOTE_FK2 FOREIGN KEY (FORNECEDORA)
        REFERENCES FORNECEDORA(CNPJ) ON DELETE CASCADE
);

CREATE TABLE COQUETEL (
    FESTA NUMBER NOT NULL,
    ORCAMENTO NUMBER(11,2) NOT NULL,
    LOCAL VARCHAR2(60) NOT NULL,
    CIDADE VARCHAR2(40) NOT NULL,
    CONSTRAINT COQUETEL_PK PRIMARY KEY (FESTA),
    CONSTRAINT COQUETEL_FK1 FOREIGN KEY (FESTA)
        REFERENCES FESTA (ID)
        ON DELETE CASCADE,
    CONSTRAINT COQUETEL_FK2 FOREIGN KEY (LOCAL, CIDADE)
        REFERENCES LOCAL (NOME, CIDADE)
        ON DELETE CASCADE
);

CREATE TABLE FORNECIMENTOCOQUETEL (
    FORNECEDORA VARCHAR2(14) NOT NULL,
    COQUETEL NUMBER NOT NULL,
    PRECO NUMBER(9,2) NOT NULL,
    CONSTRAINT FORNECIMENTOCOQUETEL_PK PRIMARY KEY (FORNECEDORA, COQUETEL),
    CONSTRAINT FORNECIMENTOCOQUETEL_FK1 FOREIGN KEY (FORNECEDORA)
        REFERENCES FORNECEDORA (CNPJ)
        ON DELETE CASCADE,
    CONSTRAINT FORNECIMENTOCOQUETEL_FK2 FOREIGN KEY (COQUETEL)
        REFERENCES COQUETEL (FESTA)
        ON DELETE CASCADE
);

CREATE TABLE PRODUTOSFORNECIDOS (
    FORNECEDORA VARCHAR2(14) NOT NULL,
    COQUETEL NUMBER NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    QUANTIDADE NUMBER NOT NULL,
    CONSTRAINT PRODUTOSFORNECIDOS_PK PRIMARY KEY (FORNECEDORA, COQUETEL, NOME),
    CONSTRAINT PRODUTOSFORNECIDOS_FK1 FOREIGN KEY (FORNECEDORA, COQUETEL)
        REFERENCES FORNECIMENTOCOQUETEL(FORNECEDORA, COQUETEL)
        ON DELETE CASCADE
);

CREATE TABLE BRINDE (
    COQUETEL NUMBER NOT NULL,
    NOME VARCHAR2(30) NOT NULL,
    DESCRICAO VARCHAR2(60) NOT NULL,
    CONSTRAINT BRINDE_PK PRIMARY KEY (COQUETEL, NOME),
    CONSTRAINT BRINDE_FK1 FOREIGN KEY (COQUETEL)
        REFERENCES COQUETEL(FESTA)
        ON DELETE CASCADE
);

CREATE TABLE CONVIDADO (
    EMAIL VARCHAR2(60) NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    TELEFONE VARCHAR2(11),
    CONSTRAINT CONVIDADO_PK PRIMARY KEY (EMAIL)
);

CREATE TABLE CONVITE (
    CONVIDADO VARCHAR2(60) NOT NULL,
    COQUETEL NUMBER NOT NULL,
    CONSTRAINT CONVITE_PK PRIMARY KEY (CONVIDADO, COQUETEL),
    CONSTRAINT CONVITE_FK1 FOREIGN KEY (CONVIDADO)
        REFERENCES CONVIDADO(EMAIL)
        ON DELETE CASCADE,
    CONSTRAINT CONVITE_FK2 FOREIGN KEY (COQUETEL)
        REFERENCES COQUETEL(FESTA)
        ON DELETE CASCADE
);

CREATE TABLE CATEGORIAFORNECIMENTO (
    NOMEREF VARCHAR2(20) NOT NULL,
    DESCRICAO VARCHAR2(140) NOT NULL,
    CONSTRAINT CATEGORIAFORNECIMENTO_PK PRIMARY KEY (NOMEREF)
);

CREATE TABLE ATRIBUICAOCATEGORIA (
    FORNECEDORA VARCHAR2(14) NOT NULL,
    CATEGORIA VARCHAR2(20) NOT NULL,
    FAIXAPRECO CHAR(1),
    CONSTRAINT ATRIBUICAOCATEGORIA_CK1 CHECK (FAIXAPRECO IN ('1', '2', '3', '4', '5')),
    CONSTRAINT ATRIBUICAOCATEGORIA_PK PRIMARY KEY (FORNECEDORA, CATEGORIA),
    CONSTRAINT ATRIBUICAOCATEGORIA_FK1 FOREIGN KEY (FORNECEDORA)
        REFERENCES FORNECEDORA (CNPJ)
        ON DELETE CASCADE,
    CONSTRAINT ATRIBUICAOCATEGORIA_FK2 FOREIGN KEY (CATEGORIA)
        REFERENCES CATEGORIAFORNECIMENTO (NOMEREF)
        ON DELETE CASCADE
);

CREATE TABLE FUNCIONARIO (
    CPF VARCHAR2(11) NOT NULL,
    RG VARCHAR2(15) NOT NULL,
    ESTADO VARCHAR2(19) NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    CIDADE VARCHAR2(40) NOT NULL,
    RUA VARCHAR2(40),
    NUMERO NUMBER,
    EMAIL VARCHAR2(60) NOT NULL,
    TELRESIDENCIAL VARCHAR2(11),
    TELCELULAR VARCHAR2(11),
    VALORPORHORA NUMBER(9,2) NOT NULL,
    FUNCAO VARCHAR2(12) NOT NULL,
    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (CPF),
    CONSTRAINT FUNCIONARIO_UN1 UNIQUE(RG, ESTADO)
);

CREATE TABLE CONTRATOCOQUETEL (
    COQUETEL NUMBER NOT NULL,
    FUNCIONARIO VARCHAR2(11) NOT NULL,
    HORASTRABALHADAS NUMBER NOT NULL,
    VALORPAGO NUMBER(9,2) NOT NULL,
    CONSTRAINT CONTRATOCOQUETEL_PK PRIMARY KEY (COQUETEL, FUNCIONARIO),
    CONSTRAINT CONTRATOCOQUETEL_FK1 FOREIGN KEY (COQUETEL)
        REFERENCES COQUETEL(FESTA)
        ON DELETE CASCADE,
    CONSTRAINT CONTRATOCOQUETEL_FK2 FOREIGN KEY (FUNCIONARIO)
        REFERENCES FUNCIONARIO(CPF)
        ON DELETE CASCADE
);

CREATE TABLE CONTRATOFESTFOOD (
    FESTFOOD NUMBER NOT NULL,
    SEGURANCA VARCHAR2(11) NOT NULL,
    HORASTRABALHADAS NUMBER NOT NULL,
    VALORPAGO NUMBER(9,2) NOT NULL,
    CONSTRAINT CONTRATOFESTFOOD_PK PRIMARY KEY (FESTFOOD, SEGURANCA),
    CONSTRAINT CONTRATOFESTFOOD_FK1 FOREIGN KEY (FESTFOOD)
        REFERENCES FESTFOOD(FESTA)
        ON DELETE CASCADE,
    CONSTRAINT CONTRATOFESTFOOD_FK2 FOREIGN KEY (SEGURANCA)
        REFERENCES FUNCIONARIO(CPF)
        ON DELETE CASCADE
);

