CREATE TABLE EMPRESA (
    CNPJ VARCHAR2(14) NOT NULL,
    NOMEFANTASIA VARCHAR2(60),
    RAZAOSOCIAL VARCHAR2(120) NOT NULL,
    ENDERECO VARCHAR2(120) NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE CONTATO_EMPRESA (
    EMPRESA VARCHAR2(14) NOT NULL,
    EMAIL VARCHAR2(60) NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    TELEFONE VARCHAR2(11),
    CONSTRAINT CONTATO_EMPRESA_PK PRIMARY KEY (EMPRESA, EMAIL),
    CONSTRAINT CONTATO_EMPRESA_FK1 FOREIGN KEY (EMPRESA)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE FORNECEDORA (
    CNPJ VARCHAR2(14) NOT NULL,
    CONSTRAINT FORNECEDORA_PK PRIMARY KEY (CNPJ),
    CONSTRAINT FORNECEDORA_FK1 FOREIGN KEY (CNPJ)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE CONTRATANTE (
    CNPJ VARCHAR2(14) NOT NULL,
    CONSTRAINT CONTRATANTE_PK PRIMARY KEY (CNPJ),
    CONSTRAINT CONTRATANTE_FK1 FOREIGN KEY (CNPJ)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE FESTA (
    ID NUMBER NOT NULL,
    CONTRATANTE VARCHAR2(14) NOT NULL,
    DATA DATE NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    HORAINICIO DATE NOT NULL,
    DURACAO DATE NOT NULL,
    TIPOFESTA VARCHAR2(8) NOT NULL,
    CONSTRAINT FESTA_PK PRIMARY KEY (ID),
    CONSTRAINT FESTA_UN1 UNIQUE (CONTRATANTE, DATA),
    CONSTRAINT FESTA_FK1 FOREIGN KEY (CONTRATANTE) REFERENCES CONTRATANTE(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FESTA_CK_TIPOFESTA CHECK(UPPER(TIPOFESTA) IN ('FESTFOOD', 'COQUETEL'))
);