CREATE TABLE EMPRESA (
    CNPJ VARCHAR2(14) NOT NULL,
    NOMEFANTASIA VARCHAR2(60),
    RAZAOSOCIAL VARCHAR2(120) NOT NULL,
    ENDERECO VARCHAR2(120) NOT NULL,
    CONSTRAINT EMPRESA_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE CONTATO_EMPRESA (
    EMPRESA VARCHAR2(14) NOT NULL,
    EMAIL VARCHAR2(60) NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    TELEFONE VARCHAR2(11),
    CONSTRAINT CONTATO_EMPRESA_PK PRIMARY KEY (EMPRESA, EMAIL),
    CONSTRAINT CONTATO_EMPRESA_FK1 FOREIGN KEY (EMPRESA)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE FORNECEDORA (
    CNPJ VARCHAR2(14) NOT NULL,
    CONSTRAINT FORNECEDORA_PK PRIMARY KEY (CNPJ),
    CONSTRAINT FORNECEDORA_FK1 FOREIGN KEY (CNPJ)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE CONTRATANTE (
    CNPJ VARCHAR2(14) NOT NULL,
    CONSTRAINT CONTRATANTE_PK PRIMARY KEY (CNPJ),
    CONSTRAINT CONTRATANTE_FK1 FOREIGN KEY (CNPJ)
        REFERENCES EMPRESA(CNPJ)
        ON DELETE CASCADE
);

CREATE TABLE FESTA (
    ID NUMBER NOT NULL,
    CONTRATANTE VARCHAR2(14) NOT NULL,
    DATA DATE NOT NULL,
    NOME VARCHAR2(60) NOT NULL,
    HORAINICIO DATE NOT NULL,
    DURACAO DATE NOT NULL,
    TIPOFESTA VARCHAR2(8) NOT NULL,
    CONSTRAINT FESTA_PK PRIMARY KEY (ID),
    CONSTRAINT FESTA_UN1 UNIQUE (CONTRATANTE, DATA),
    CONSTRAINT FESTA_FK1 FOREIGN KEY (CONTRATANTE) REFERENCES CONTRATANTE(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FESTA_CK_TIPOFESTA CHECK(UPPER(TIPOFESTA) IN ('FESTFOOD', 'COQUETEL'))
);

CREATE TABLE FESTFOOD (
    FESTA NUMBER NOT NULL,
    PRECOINGRESSO NUMBER(6,2) NOT NULL,
    CONSTRAINT FESTFOOD_PK PRIMARY KEY (FESTA),
    CONSTRAINT FESTFOOD_FK1 FOREIGN KEY (FESTA) REFERENCES FESTA(ID) ON DELETE CASCADE,
    CONSTRAINT FESTFOOD_CK_PRECOINGRESSO CHECK(PRECOINGRESSO >= 0)
);

CREATE TABLE INGRESSO (
    FESTFOOD NUMBER NOT NULL,
    NUMERO NUMBER NOT NULL,
    CPFCOMPRADOR VARCHAR2(11) NOT NULL,
    CONSTRAINT INGRESSO_PK PRIMARY KEY (FESTFOOD, NUMERO),
    CONSTRAINT INGRESSO_FK1 FOREIGN KEY (FESTFOOD) REFERENCES FESTFOOD(FESTA) ON DELETE CASCADE
);

CREATE TABLE LOCAL (
    NOME VARCHAR2(60) NOT NULL,
    CIDADE VARCHAR2(40) NOT NULL,
    ESTADO VARCHAR2(19) NOT NULL,
    RUA VARCHAR2(40) NOT NULL,
    NUMERO NUMBER NOT NULL,
    MAXFREQUENTADORES NUMBER NOT NULL,
    POSSUIABERTURA CHAR(1) NOT NULL,
    DIARIALOCACAO NUMBER(9, 2) NOT NULL,
    CONSTRAINT LOCAL_CK_POSSUIABERTURA CHECK(UPPER(POSSUIABERTURA) IN ('V', 'F')),
    CONSTRAINT LOCAL_PK PRIMARY KEY (NOME, CIDADE)
);

CREATE TABLE LOCACAO (
    ID NUMBER NOT NULL,
    FESTFOOD NUMBER NOT NULL,
    NOMELOCAL VARCHAR2(60) NOT NULL,
    CIDADELOCAL VARCHAR2(40) NOT NULL,
    CONSTRAINT LOCACAO_PK PRIMARY KEY (ID),
    CONSTRAINT LOCACAO_UN1 UNIQUE(FESTFOOD, NOMELOCAL, CIDADELOCAL),
    CONSTRAINT LOCACAO_FK1 FOREIGN KEY (FESTFOOD)
        REFERENCES FESTFOOD(FESTA)
        ON DELETE CASCADE,
    CONSTRAINT LOCACAO_FK2 FOREIGN KEY (NOMELOCAL, CIDADELOCAL)
        REFERENCES LOCAL(NOME, CIDADE)
        ON DELETE CASCADE
);

CREATE TABLE LOTE (
    LOCACAO NUMBER NOT NULL,
    NUMERO NUMBER NOT NULL,
    FORNECEDORA VARCHAR2(14),
    PRECO NUMBER(9, 2) NOT NULL,
    LARGURA NUMBER(6,2),
    COMPRIMENTO NUMBER(6,2),
    CONSTRAINT LOTE_CK_LARGURA CHECK(LARGURA > 0),
    CONSTRAINT LOTE_CK_COMPRIMENTO CHECK(COMPRIMENTO > 0),
    CONSTRAINT LOTE_PK PRIMARY KEY (NUMERO, LOCACAO),
    CONSTRAINT LOTE_FK1 FOREIGN KEY (LOCACAO)
        REFERENCES LOCACAO(ID) ON DELETE CASCADE,
    CONSTRAINT LOTE_FK2 FOREIGN KEY (FORNECEDORA)
        REFERENCES FORNECEDORA(CNPJ) ON DELETE CASCADE
);
