-- COMANDOS PARA RESETAR O BANCO DE DADOS (APAGAR TODAS AS TABELAS/PROCEDURES/TRIGGERS)
-- USADA APENAS DURANTE O DESENVOLVIMENTO

DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE CONTATOEMPRESA CASCADE CONSTRAINTS;
DROP TABLE FORNECEDORA CASCADE CONSTRAINTS;
DROP TABLE CONTRATANTE CASCADE CONSTRAINTS;
DROP TABLE FESTA CASCADE CONSTRAINTS;
DROP TABLE FESTFOOD CASCADE CONSTRAINTS;
DROP TABLE INGRESSO CASCADE CONSTRAINTS;
DROP TABLE LOCAL CASCADE CONSTRAINTS;
DROP TABLE LOCACAO CASCADE CONSTRAINTS;
DROP TABLE LOTE CASCADE CONSTRAINTS;
DROP TABLE COQUETEL CASCADE CONSTRAINTS;
DROP TABLE FORNECIMENTOCOQUETEL CASCADE CONSTRAINTS;
DROP TABLE PRODUTOSFORNECIDOS CASCADE CONSTRAINTS;
DROP TABLE BRINDE CASCADE CONSTRAINTS;
DROP TABLE CONVIDADO CASCADE CONSTRAINTS;
DROP TABLE CONVITE CASCADE CONSTRAINTS;
DROP TABLE CATEGORIAFORNECIMENTO CASCADE CONSTRAINTS;
DROP TABLE ATRIBUICAOCATEGORIA CASCADE CONSTRAINTS;
DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS;
DROP TABLE CONTRATOCOQUETEL CASCADE CONSTRAINTS;
DROP TABLE CONTRATOFESTFOOD CASCADE CONSTRAINTS;

DROP TRIGGER FESTA_AUTOINCREMENTO;
DROP SEQUENCE FESTA_ID_SEQ;

DROP TRIGGER LOCACAO_AUTOINCREMENTO;
DROP SEQUENCE LOCACAO_ID_SEQ;

DROP TRIGGER CONTRATOCOQUETEL_VALORPAGO;
DROP TRIGGER CONTRATOFESTFOOD_VALORPAGO;
DROP FUNCTION CONTRATO_CALCULAVALORPAGO;

DROP PROCEDURE COQUETEL_CALCULAORCAMENTO;
