DROP TABLE EMPRESA CASCADE CONSTRAINTS;
DROP TABLE CONTATO_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE FORNECEDORA CASCADE CONSTRAINTS;
DROP TABLE CONTRATANTE CASCADE CONSTRAINTS;
DROP TABLE FESTA CASCADE CONSTRAINTS;