CREATE SEQUENCE FESTA_ID_SEQ
    START WITH 10;
    
CREATE SEQUENCE LOCACAO_ID_SEQ
    START WITH 10;

CREATE OR REPLACE TRIGGER FESTA_AUTOINCREMENTO
    BEFORE INSERT ON FESTA
    FOR EACH ROW
    
    BEGIN
        IF (:NEW.ID IS NULL) THEN
            SELECT FESTA_ID_SEQ.NEXTVAL
                INTO :NEW.ID
                FROM DUAL;
        END IF;
    END;
/

CREATE OR REPLACE TRIGGER LOCACAO_AUTOINCREMENTO
    BEFORE INSERT ON LOCACAO
    FOR EACH ROW
    
    BEGIN
        IF :NEW.ID IS NULL THEN
            SELECT LOCACAO_ID_SEQ.NEXTVAL
            INTO :NEW.ID
            FROM DUAL;  
        END IF;
    END;  
/

CREATE OR REPLACE FUNCTION CONTRATO_CALCULAVALORPAGO (FUNC IN VARCHAR2, HORASTRAB IN NUMBER) 
    RETURN NUMBER
    IS VALPORHORA NUMBER(9,2);
    
    BEGIN
        SELECT MAX(VALORPORHORA)
            INTO VALPORHORA
            FROM FUNCIONARIO
            WHERE FUNC = FUNCIONARIO.CPF
            ORDER BY FUNCIONARIO.CPF;
        
        RETURN (VALPORHORA * HORASTRAB);
    END;
/

CREATE OR REPLACE TRIGGER CONTRATOCOQUETEL_VALORPAGO
    BEFORE INSERT OR UPDATE ON CONTRATOCOQUETEL
    FOR EACH ROW
    
    BEGIN
        IF (:NEW.VALORPAGO IS NULL) THEN
            SELECT CONTRATO_CALCULAVALORPAGO(:NEW.FUNCIONARIO, :NEW.HORASTRABALHADAS)
            INTO :NEW.VALORPAGO
            FROM DUAL;
        END IF;
    END;
/

CREATE OR REPLACE TRIGGER CONTRATOFESTFOOD_VALORPAGO
    BEFORE INSERT OR UPDATE ON CONTRATOFESTFOOD
    FOR EACH ROW
    
    BEGIN
        IF (:NEW.VALORPAGO IS NULL) THEN
            SELECT CONTRATO_CALCULAVALORPAGO(:NEW.SEGURANCA, :NEW.HORASTRABALHADAS)
            INTO :NEW.VALORPAGO
            FROM DUAL;
        END IF;
    END;
/

CREATE OR REPLACE PROCEDURE COQUETEL_CALCULAORCAMENTO (ID_COQ NUMBER)
    IS FORNECIMENTO NUMBER(9,2);
        DIARIA NUMBER(9,2);
        PAGAMENTOS NUMBER(9,2);
    BEGIN
        -- FORNECIMENTO DE ALIMENTOS
        SELECT SUM(PRECO)
            INTO FORNECIMENTO
            FROM FORNECIMENTOCOQUETEL
            WHERE COQUETEL = ID_COQ;         

        IF (FORNECIMENTO IS NULL) THEN FORNECIMENTO := 0.0; END IF;

       -- DIARIA DA LOCACAO
        SELECT L.DIARIALOCACAO
                INTO DIARIA
                FROM LOCAL L, COQUETEL COQ
                WHERE L.NOME = COQ.LOCAL
                    AND L.CIDADE = COQ.CIDADE
                    AND COQ.FESTA = ID_COQ;
                    
        IF (DIARIA IS NULL) THEN DIARIA := 0.0; END IF;

       -- PAGAMENTO DE FUNCIONARIOS
       SELECT SUM(VALORPAGO)
            INTO PAGAMENTOS
            FROM CONTRATOCOQUETEL
            WHERE COQUETEL = ID_COQ;
            
        IF (PAGAMENTOS IS NULL) THEN PAGAMENTOS := 0.0; END IF;

        -- ATUALIZAR ORCAMENTO
        UPDATE COQUETEL 
            SET ORCAMENTO = (FORNECIMENTO + DIARIA + PAGAMENTOS)
            WHERE FESTA = ID_COQ;
    END;
/