CREATE SEQUENCE FESTA_ID_SEQ
    START WITH 10;
    
CREATE SEQUENCE LOCACAO_ID_SEQ
    START WITH 10;

CREATE TRIGGER FESTA_AUTOINCREMENTO
    BEFORE INSERT ON FESTA
    FOR EACH ROW
    
    BEGIN
        IF (:NEW.ID IS NULL) THEN
            SELECT FESTA_ID_SEQ.NEXTVAL
                INTO :NEW.ID
                FROM DUAL;
        END IF;
    END;
/

CREATE TRIGGER LOCACAO_AUTOINCREMENTO
    BEFORE INSERT ON LOCACAO
    FOR EACH ROW
    
    BEGIN
        IF :NEW.ID IS NULL THEN
            SELECT LOCACAO_ID_SEQ.NEXTVAL
            INTO :NEW.ID
            FROM DUAL;  
        END IF;
    END;  
/

CREATE FUNCTION CONTRATO_CALCULAVALORPAGO (FUNC IN VARCHAR2, HORASTRAB IN NUMBER) 
    RETURN NUMBER
    IS VALPORHORA NUMBER(9,2);
    
    BEGIN
        SELECT MAX(VALORPORHORA)
            INTO VALPORHORA
            FROM FUNCIONARIO
            WHERE FUNC = FUNCIONARIO.CPF
            ORDER BY FUNCIONARIO.CPF;
        
        RETURN (VALPORHORA * HORASTRAB);
    END;
/

CREATE TRIGGER CONTRATOCOQUETEL_VALORPAGO
    BEFORE INSERT OR UPDATE ON CONTRATOCOQUETEL
    FOR EACH ROW
    
    BEGIN
        IF (:NEW.VALORPAGO IS NULL) THEN
            SELECT CONTRATO_CALCULAVALORPAGO(:NEW.FUNCIONARIO, :NEW.HORASTRABALHADAS)
            INTO :NEW.VALORPAGO
            FROM DUAL;
        END IF;
    END;
/

CREATE TRIGGER CONTRATOFESTFOOD_VALORPAGO
    BEFORE INSERT OR UPDATE ON CONTRATOFESTFOOD
    FOR EACH ROW
    
    BEGIN
        IF (:NEW.VALORPAGO IS NULL) THEN
            SELECT CONTRATO_CALCULAVALORPAGO(:NEW.SEGURANCA, :NEW.HORASTRABALHADAS)
            INTO :NEW.VALORPAGO
            FROM DUAL;
        END IF;
    END;
/

